- name: view registry keys to see if server needs auto reboot
  win_reg_stat: 
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired
    name: UpdateExeVolatile
  register: view_sccm
  ignore_errors: yes 

- name: View if sccm keys are defined
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Updates\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\
    name: RebootRequired
  register: view_updates
  ignore_errors: yes 

- name: wmi command
  shell: Invoke-WmiMethod -ComputerName $MachineName -Namespace root\ccm\clientsdk -Class CCM_ClientUtilities -Name DetermineIfRebootPending -ErrorAction SilentlyContinue ).RebootPending
  register: shell_out

- name: Output of the keys sccm
  debug:
    var: view_sccm
- name: Output of the keys updates
  debug:
    var: view_updates
- name: shell out
  debug:
    var: shell_out