- name: view registry keys to see if server needs auto reboot
  win_reg_stat: 
    path: HKLM\Software\Microsoft\Updates
    name: UpdateExeVolatile
  register: current_auto
  ignore_errors: yes 

- name: view registry keys to see if server needs auto reboot
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired
  register: view_updates
  ignore_errors: yes 

- name: check if SCCM client indicates that server needs a restart through WMI command
  win_shell: (Invoke-WmiMethod -Namespace root\ccm\clientsdk -Class CCM_ClientUtilities -Name DetermineIfRebootPending -ErrorAction SilentlyContinue ).RebootPending
  register: shell_out
  ignore_errors: yes

- name: output servers
  debug:
    var: ansible_hostname
  when: shell_out|lower == "true" or view_updates.exists|lower == "true" or current_auto.value >= "0"


# - name: Output of the keys sccm
#   debug:
#     var: view_sccm
# - name: Output of the keys updates
#   debug:
#     var: view_updates
# - name: shell out
#   debug:
#     var: shell_out