---
- name: Create Approval rule and add computers to new approval group
  hosts: all
  gather_facts: yes
  tasks:
    - name: run approval rule
      win_dsc:
        resource_name: UpdateServicesApprovalRule 
        Ensure: yes
        Name: Default
    # - name: Install WSUS DSC modules
    #   win_psmodule:
    #     name: MSFT_UpdateServicesDsc 
    #     state: present
    #   delegate_to: "{{ query('inventory_hostnames', 'wsus')[0] }}"

    - name: Make sure servers in WSUS Target group
      win_shell: Get-WsusComputer -NameIncludes {{ item }} | Add-WsusComputer -TargetGroupName {{ wsus_target_group | default('test01')}}
      loop: "{{ groups['patching'] }}"
      delegate_to: "{{ query('inventory_hostnames', 'wsus')[0] }}"
    


