---
- name: Create Approval rule and add computers to new approval group
  hosts: all
  gather_facts: yes
  tasks:

    - name: Setup the xWebAdministration module
      win_psmodule:
        name: xWebAdministration
        state: present

    - name: Create IIS Website with Binding and Authentication options
      win_dsc:
        resource_name: xWebsite
        Ensure: Present
        Name: DSC Website
        State: Started
        PhysicalPath: C:\inetpub\wwwroot
        BindingInfo: # Example of a CimInstance[] DSC parameter (list of dicts)
        - Protocol: https
          Port: 1234
          CertificateStoreName: MY
          CertificateThumbprint: C676A89018C4D5902353545343634F35E6B3A659
          HostName: DSCTest
          IPAddress: '*'
          SSLFlags: '1'
        - Protocol: http
          Port: 4321
          IPAddress: '*'
        AuthenticationInfo: # Example of a CimInstance DSC parameter (dict)
          Anonymous: no
          Basic: true
          Digest: false
          Windows: yes






    - name: run approval rule
      win_dsc:
        resource_name: UpdateServicesApprovalRule 
        Ensure: yes
        Name: Default
      delegate_to: "{{ query('inventory_hostnames', 'wsus')[0] }}"
    # - name: Install WSUS DSC modules
    #   win_psmodule:
    #     name: MSFT_UpdateServicesDsc 
    #     state: present
    #   delegate_to: "{{ query('inventory_hostnames', 'wsus')[0] }}"

    - name: Make sure servers in WSUS Target group
      win_shell: Get-WsusComputer -NameIncludes {{ item }} | Add-WsusComputer -TargetGroupName {{ wsus_target_group | default('test01')}}
      loop: "{{ groups['patching'] }}"
      delegate_to: "{{ query('inventory_hostnames', 'wsus')[0] }}"
    


