---

- name: check WSMan CredSSP status
  win_shell: Get-ChildItem -path WSMan:\localhost\Service\Auth\CredSSP
  register: wsman_credssp

- name: check WSMan Basic status
  win_shell: Get-ChildItem -path WSMan:\localhost\Service\Auth\Basic
  register: wsman_basic

- name: Apply credssp transport cert and settings with Ansible script
  script: files/windows_transport.ps1 -EnableCredSSP -DisableBasicAuth  #-ForceNewSSLCert
  when: "'false' in wsman_basic and 'false' in wsman_credssp"  